mock-repos:
	- mockgen -source repository/example_repository.go -destination repository/mocks/example_repository.go -package mocks
	- mockgen -source repository/tx.go -destination repository/mocks/tx.go -package mocks