mock-repos:
	- mockgen -source repository/example_repository.go -destination repository/mocks/example_repository.go -package mocks
	- mockgen -source repository/repository_manager.go -destination repository/mocks/repository_manager.go -package mocks