// Code generated by mockery v2.43.2. DO NOT EDIT.

package pkga

import mock "github.com/stretchr/testify/mock"

// MockInterfaceA is an autogenerated mock type for the InterfaceA type
type MockInterfaceA struct {
	mock.Mock
}

type MockInterfaceA_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterfaceA) EXPECT() *MockInterfaceA_Expecter {
	return &MockInterfaceA_Expecter{mock: &_m.Mock}
}

// MethodA provides a mock function with given fields:
func (_m *MockInterfaceA) MethodA() {
	_m.Called()
}

// MockInterfaceA_MethodA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MethodA'
type MockInterfaceA_MethodA_Call struct {
	*mock.Call
}

// MethodA is a helper method to define mock.On call
func (_e *MockInterfaceA_Expecter) MethodA() *MockInterfaceA_MethodA_Call {
	return &MockInterfaceA_MethodA_Call{Call: _e.mock.On("MethodA")}
}

func (_c *MockInterfaceA_MethodA_Call) Run(run func()) *MockInterfaceA_MethodA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterfaceA_MethodA_Call) Return() *MockInterfaceA_MethodA_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterfaceA_MethodA_Call) RunAndReturn(run func()) *MockInterfaceA_MethodA_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterfaceA creates a new instance of MockInterfaceA. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterfaceA(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterfaceA {
	mock := &MockInterfaceA{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
